//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.15 at 05:00:52 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.turntabl.io/producer/clientOrders", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package io.turntabl.producer.clientorders;
